version: '3.8'
# ---------- AUTH STACK ----------
services:
  auth-postgres:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - '5433:5432'
    networks:
      - auth-network

  auth-redis:
    image: redis:7
    container_name: auth-redis
    ports:
      - '6381:6379'
    networks:
      - auth-network

  auth-zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: auth-zookeeper
    ports:
      - '2182:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - auth-network

  auth-kafka:
    image: bitnami/kafka:3.7.0
    container_name: auth-kafka
    ports:
      - '9093:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: auth-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    depends_on:
      - auth-zookeeper
    networks:
      - auth-network

  auth-service:
    build: .
    container_name: auth-service
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@auth-postgres:5432/authdb
      REDIS_URL: redis://auth-redis:6379
      KAFKA_BROKER: auth-kafka:9092
      JWT_SECRET: 01aee198bd1475f54ba9fbc7663430a8e659d8755b550fcb322008f0f66d3719
      JWT_EXPIRES_IN: 24h
      LOG_LEVEL: debug
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:8000,http://localhost:8001,http://localhost:8002,http://localhost:8003,http://localhost:8004
      SENTRY_DSN: https://96f53729f88ff3c970a9d10448c277cb@o4510035651395584.ingest.de.sentry.io/4510038750986320
      SENTRY_ENVIRONMENT: development
      SENTRY_SAMPLE_RATE: 1.0
      SENTRY_TRACES_SAMPLE_RATE: 1.0
    depends_on:
      - auth-postgres
      - auth-redis
      - auth-kafka
    restart: unless-stopped
    networks:
      - auth-network

volumes:
  postgres-data:
  redis-data:

networks:
  auth-network:
    driver: bridge
